// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYKOVjgO1-jC0P6GQ1-Dn1U6AxWtPhyGs',
    appId: '1:655454790901:android:d02afe4406198e5897d1bc',
    messagingSenderId: '655454790901',
    projectId: 'koontaa-7a1a5',
    storageBucket: 'koontaa-7a1a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGJyvGSwJDDkEc7lyUmI9iois2DoArhr0',
    appId: '1:655454790901:ios:25b3f787f62f71b797d1bc',
    messagingSenderId: '655454790901',
    projectId: 'koontaa-7a1a5',
    storageBucket: 'koontaa-7a1a5.firebasestorage.app',
    androidClientId:
        '655454790901-rnn76hcg0ciq10u6ic92otn4ds2gfc3k.apps.googleusercontent.com',
    iosClientId:
        '655454790901-o4upr0pj1lu3hgi7lksctj01vkncggjh.apps.googleusercontent.com',
    iosBundleId: 'com.example.koontaa',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5bgU9FdNT5jUBBZPr3Xq1z7XMavGwthE',
    appId: '1:655454790901:web:be44a0c5fc52c98797d1bc',
    messagingSenderId: '655454790901',
    projectId: 'koontaa-7a1a5',
    authDomain: 'koontaa-7a1a5.firebaseapp.com',
    storageBucket: 'koontaa-7a1a5.firebasestorage.app',
    measurementId: 'G-DEVEZJFLCG',
  );
}
